services:
  tmfapi_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  tmfapi_app:
    image: tmfapi
    build: .
    ports:
      - "8000:8000"
    depends_on:
      tmfapi_database:
        condition: service_healthy
    env_file:
      - .env

volumes:
  pgdata: