[tool.pytest.ini_options]
pythonpath = '.'
addopts = "-p no:warning"
testpaths = ["tests"]
asyncio_default_fixture_loop_scope = "function"

[tool.taskipy.tasks]
run = 'PYTHONPATH=./ fastapi dev app.py'
test = 'pytest'