[tool.pytest.ini_options]
pythonpath = '.'
addopts = "-p no:warning"
testpaths = ["tests"]
asyncio_default_fixture_loop_scope = "function"

[tool.taskipy.tasks]
run = 'PYTHONPATH=./ fastapi dev app.py'
run_lan = 'PYTHONPATH=./ fastapi dev app.py --host 0.0.0.0'
test = 'PYTHONPATH=./ pytest -s -x --cov=src -vv'